# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Hello.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bHello.proto\"k\n\nSimpleType\x12\x0f\n\x07int_num\x18\x01 \x01(\x05\x12\x11\n\tfloat_num\x18\x02 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x16\n\tbool_flag\x18\x04 \x01(\x08H\x00\x88\x01\x01\x42\x0c\n\n_bool_flag\"@\n\x0b\x45numeration\"1\n\x08pick_one\x12\x0b\n\x07\x43HOICE0\x10\x00\x12\x0b\n\x07\x43HOICE1\x10\x01\x12\x0b\n\x07\x43HOICE2\x10\x02\"\x1c\n\x08ListType\x12\x10\n\x08int_list\x18\x01 \x03(\x05\":\n\nNestedType\x1a,\n\x0bRequestType\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\xa7\x01\n\x07MapType\x12 \n\x04map1\x18\x01 \x03(\x0b\x32\x12.MapType.Map1Entry\x12 \n\x04map2\x18\x02 \x03(\x0b\x32\x12.MapType.Map2Entry\x1a+\n\tMap1Entry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a+\n\tMap2Entry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"1\n\tOneofType\x12\x0e\n\x04text\x18\x01 \x01(\tH\x00\x12\r\n\x03num\x18\x02 \x01(\x05H\x00\x42\x05\n\x03one\",\n\x0bRequestType\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\" \n\x0cResponseType\x12\x10\n\x08sentence\x18\x01 \x01(\t2\xa8\x03\n\x04Test\x12(\n\nTypeSimple\x12\x0b.SimpleType\x1a\x0b.SimpleType\"\x00\x12(\n\x08TypeEnum\x12\x0c.Enumeration\x1a\x0c.Enumeration\"\x00\x12\"\n\x08TypeList\x12\t.ListType\x1a\t.ListType\"\x00\x12(\n\nTypeNested\x12\x0b.NestedType\x1a\x0b.NestedType\"\x00\x12\x1f\n\x07TypeMap\x12\x08.MapType\x1a\x08.MapType\"\x00\x12%\n\tTypeOneof\x12\n.OneofType\x1a\n.OneofType\"\x00\x12*\n\tSayHello0\x12\x0c.RequestType\x1a\r.ResponseType\"\x00\x12,\n\tSayHello1\x12\x0c.RequestType\x1a\r.ResponseType\"\x00(\x01\x12,\n\tSayHello2\x12\x0c.RequestType\x1a\r.ResponseType\"\x00\x30\x01\x12.\n\tSayHello3\x12\x0c.RequestType\x1a\r.ResponseType\"\x00(\x01\x30\x01\x62\x06proto3'
)



_ENUMERATION_PICK_ONE = _descriptor.EnumDescriptor(
  name='pick_one',
  full_name='Enumeration.pick_one',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHOICE0', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHOICE1', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHOICE2', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=139,
  serialized_end=188,
)
_sym_db.RegisterEnumDescriptor(_ENUMERATION_PICK_ONE)


_SIMPLETYPE = _descriptor.Descriptor(
  name='SimpleType',
  full_name='SimpleType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='int_num', full_name='SimpleType.int_num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='float_num', full_name='SimpleType.float_num', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='SimpleType.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bool_flag', full_name='SimpleType.bool_flag', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_bool_flag', full_name='SimpleType._bool_flag',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=15,
  serialized_end=122,
)


_ENUMERATION = _descriptor.Descriptor(
  name='Enumeration',
  full_name='Enumeration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENUMERATION_PICK_ONE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=188,
)


_LISTTYPE = _descriptor.Descriptor(
  name='ListType',
  full_name='ListType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='int_list', full_name='ListType.int_list', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=218,
)


_NESTEDTYPE_REQUESTTYPE = _descriptor.Descriptor(
  name='RequestType',
  full_name='NestedType.RequestType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='NestedType.RequestType.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='NestedType.RequestType.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=278,
)

_NESTEDTYPE = _descriptor.Descriptor(
  name='NestedType',
  full_name='NestedType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_NESTEDTYPE_REQUESTTYPE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=278,
)


_MAPTYPE_MAP1ENTRY = _descriptor.Descriptor(
  name='Map1Entry',
  full_name='MapType.Map1Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MapType.Map1Entry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='MapType.Map1Entry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=403,
)

_MAPTYPE_MAP2ENTRY = _descriptor.Descriptor(
  name='Map2Entry',
  full_name='MapType.Map2Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='MapType.Map2Entry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='MapType.Map2Entry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=405,
  serialized_end=448,
)

_MAPTYPE = _descriptor.Descriptor(
  name='MapType',
  full_name='MapType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='map1', full_name='MapType.map1', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='map2', full_name='MapType.map2', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_MAPTYPE_MAP1ENTRY, _MAPTYPE_MAP2ENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=448,
)


_ONEOFTYPE = _descriptor.Descriptor(
  name='OneofType',
  full_name='OneofType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='OneofType.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num', full_name='OneofType.num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='one', full_name='OneofType.one',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=450,
  serialized_end=499,
)


_REQUESTTYPE = _descriptor.Descriptor(
  name='RequestType',
  full_name='RequestType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RequestType.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='RequestType.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=278,
)


_RESPONSETYPE = _descriptor.Descriptor(
  name='ResponseType',
  full_name='ResponseType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='ResponseType.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=579,
)

_SIMPLETYPE.oneofs_by_name['_bool_flag'].fields.append(
  _SIMPLETYPE.fields_by_name['bool_flag'])
_SIMPLETYPE.fields_by_name['bool_flag'].containing_oneof = _SIMPLETYPE.oneofs_by_name['_bool_flag']
_ENUMERATION_PICK_ONE.containing_type = _ENUMERATION
_NESTEDTYPE_REQUESTTYPE.containing_type = _NESTEDTYPE
_MAPTYPE_MAP1ENTRY.containing_type = _MAPTYPE
_MAPTYPE_MAP2ENTRY.containing_type = _MAPTYPE
_MAPTYPE.fields_by_name['map1'].message_type = _MAPTYPE_MAP1ENTRY
_MAPTYPE.fields_by_name['map2'].message_type = _MAPTYPE_MAP2ENTRY
_ONEOFTYPE.oneofs_by_name['one'].fields.append(
  _ONEOFTYPE.fields_by_name['text'])
_ONEOFTYPE.fields_by_name['text'].containing_oneof = _ONEOFTYPE.oneofs_by_name['one']
_ONEOFTYPE.oneofs_by_name['one'].fields.append(
  _ONEOFTYPE.fields_by_name['num'])
_ONEOFTYPE.fields_by_name['num'].containing_oneof = _ONEOFTYPE.oneofs_by_name['one']
DESCRIPTOR.message_types_by_name['SimpleType'] = _SIMPLETYPE
DESCRIPTOR.message_types_by_name['Enumeration'] = _ENUMERATION
DESCRIPTOR.message_types_by_name['ListType'] = _LISTTYPE
DESCRIPTOR.message_types_by_name['NestedType'] = _NESTEDTYPE
DESCRIPTOR.message_types_by_name['MapType'] = _MAPTYPE
DESCRIPTOR.message_types_by_name['OneofType'] = _ONEOFTYPE
DESCRIPTOR.message_types_by_name['RequestType'] = _REQUESTTYPE
DESCRIPTOR.message_types_by_name['ResponseType'] = _RESPONSETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleType = _reflection.GeneratedProtocolMessageType('SimpleType', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLETYPE,
  '__module__' : 'Hello_pb2'
  # @@protoc_insertion_point(class_scope:SimpleType)
  })
_sym_db.RegisterMessage(SimpleType)

Enumeration = _reflection.GeneratedProtocolMessageType('Enumeration', (_message.Message,), {
  'DESCRIPTOR' : _ENUMERATION,
  '__module__' : 'Hello_pb2'
  # @@protoc_insertion_point(class_scope:Enumeration)
  })
_sym_db.RegisterMessage(Enumeration)

ListType = _reflection.GeneratedProtocolMessageType('ListType', (_message.Message,), {
  'DESCRIPTOR' : _LISTTYPE,
  '__module__' : 'Hello_pb2'
  # @@protoc_insertion_point(class_scope:ListType)
  })
_sym_db.RegisterMessage(ListType)

NestedType = _reflection.GeneratedProtocolMessageType('NestedType', (_message.Message,), {

  'RequestType' : _reflection.GeneratedProtocolMessageType('RequestType', (_message.Message,), {
    'DESCRIPTOR' : _NESTEDTYPE_REQUESTTYPE,
    '__module__' : 'Hello_pb2'
    # @@protoc_insertion_point(class_scope:NestedType.RequestType)
    })
  ,
  'DESCRIPTOR' : _NESTEDTYPE,
  '__module__' : 'Hello_pb2'
  # @@protoc_insertion_point(class_scope:NestedType)
  })
_sym_db.RegisterMessage(NestedType)
_sym_db.RegisterMessage(NestedType.RequestType)

MapType = _reflection.GeneratedProtocolMessageType('MapType', (_message.Message,), {

  'Map1Entry' : _reflection.GeneratedProtocolMessageType('Map1Entry', (_message.Message,), {
    'DESCRIPTOR' : _MAPTYPE_MAP1ENTRY,
    '__module__' : 'Hello_pb2'
    # @@protoc_insertion_point(class_scope:MapType.Map1Entry)
    })
  ,

  'Map2Entry' : _reflection.GeneratedProtocolMessageType('Map2Entry', (_message.Message,), {
    'DESCRIPTOR' : _MAPTYPE_MAP2ENTRY,
    '__module__' : 'Hello_pb2'
    # @@protoc_insertion_point(class_scope:MapType.Map2Entry)
    })
  ,
  'DESCRIPTOR' : _MAPTYPE,
  '__module__' : 'Hello_pb2'
  # @@protoc_insertion_point(class_scope:MapType)
  })
_sym_db.RegisterMessage(MapType)
_sym_db.RegisterMessage(MapType.Map1Entry)
_sym_db.RegisterMessage(MapType.Map2Entry)

OneofType = _reflection.GeneratedProtocolMessageType('OneofType', (_message.Message,), {
  'DESCRIPTOR' : _ONEOFTYPE,
  '__module__' : 'Hello_pb2'
  # @@protoc_insertion_point(class_scope:OneofType)
  })
_sym_db.RegisterMessage(OneofType)

RequestType = _reflection.GeneratedProtocolMessageType('RequestType', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTTYPE,
  '__module__' : 'Hello_pb2'
  # @@protoc_insertion_point(class_scope:RequestType)
  })
_sym_db.RegisterMessage(RequestType)

ResponseType = _reflection.GeneratedProtocolMessageType('ResponseType', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSETYPE,
  '__module__' : 'Hello_pb2'
  # @@protoc_insertion_point(class_scope:ResponseType)
  })
_sym_db.RegisterMessage(ResponseType)


_MAPTYPE_MAP1ENTRY._options = None
_MAPTYPE_MAP2ENTRY._options = None

_TEST = _descriptor.ServiceDescriptor(
  name='Test',
  full_name='Test',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=582,
  serialized_end=1006,
  methods=[
  _descriptor.MethodDescriptor(
    name='TypeSimple',
    full_name='Test.TypeSimple',
    index=0,
    containing_service=None,
    input_type=_SIMPLETYPE,
    output_type=_SIMPLETYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TypeEnum',
    full_name='Test.TypeEnum',
    index=1,
    containing_service=None,
    input_type=_ENUMERATION,
    output_type=_ENUMERATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TypeList',
    full_name='Test.TypeList',
    index=2,
    containing_service=None,
    input_type=_LISTTYPE,
    output_type=_LISTTYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TypeNested',
    full_name='Test.TypeNested',
    index=3,
    containing_service=None,
    input_type=_NESTEDTYPE,
    output_type=_NESTEDTYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TypeMap',
    full_name='Test.TypeMap',
    index=4,
    containing_service=None,
    input_type=_MAPTYPE,
    output_type=_MAPTYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TypeOneof',
    full_name='Test.TypeOneof',
    index=5,
    containing_service=None,
    input_type=_ONEOFTYPE,
    output_type=_ONEOFTYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SayHello0',
    full_name='Test.SayHello0',
    index=6,
    containing_service=None,
    input_type=_REQUESTTYPE,
    output_type=_RESPONSETYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SayHello1',
    full_name='Test.SayHello1',
    index=7,
    containing_service=None,
    input_type=_REQUESTTYPE,
    output_type=_RESPONSETYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SayHello2',
    full_name='Test.SayHello2',
    index=8,
    containing_service=None,
    input_type=_REQUESTTYPE,
    output_type=_RESPONSETYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SayHello3',
    full_name='Test.SayHello3',
    index=9,
    containing_service=None,
    input_type=_REQUESTTYPE,
    output_type=_RESPONSETYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEST)

DESCRIPTOR.services_by_name['Test'] = _TEST

# @@protoc_insertion_point(module_scope)
