# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Sum.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Sum.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tSum.proto\"+\n\rRequestForSum\x12\x0c\n\x04num1\x18\x01 \x01(\x02\x12\x0c\n\x04num2\x18\x02 \x01(\x02\"!\n\x0eResponseForSum\x12\x0f\n\x07sum_num\x18\x01 \x01(\x02\x32\x35\n\tMyService\x12(\n\x03Sum\x12\x0e.RequestForSum\x1a\x0f.ResponseForSum\"\x00\x62\x06proto3'
)




_REQUESTFORSUM = _descriptor.Descriptor(
  name='RequestForSum',
  full_name='RequestForSum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num1', full_name='RequestForSum.num1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='num2', full_name='RequestForSum.num2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=56,
)


_RESPONSEFORSUM = _descriptor.Descriptor(
  name='ResponseForSum',
  full_name='ResponseForSum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sum_num', full_name='ResponseForSum.sum_num', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['RequestForSum'] = _REQUESTFORSUM
DESCRIPTOR.message_types_by_name['ResponseForSum'] = _RESPONSEFORSUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestForSum = _reflection.GeneratedProtocolMessageType('RequestForSum', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTFORSUM,
  '__module__' : 'Sum_pb2'
  # @@protoc_insertion_point(class_scope:RequestForSum)
  })
_sym_db.RegisterMessage(RequestForSum)

ResponseForSum = _reflection.GeneratedProtocolMessageType('ResponseForSum', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEFORSUM,
  '__module__' : 'Sum_pb2'
  # @@protoc_insertion_point(class_scope:ResponseForSum)
  })
_sym_db.RegisterMessage(ResponseForSum)



_MYSERVICE = _descriptor.ServiceDescriptor(
  name='MyService',
  full_name='MyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=93,
  serialized_end=146,
  methods=[
  _descriptor.MethodDescriptor(
    name='Sum',
    full_name='MyService.Sum',
    index=0,
    containing_service=None,
    input_type=_REQUESTFORSUM,
    output_type=_RESPONSEFORSUM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MYSERVICE)

DESCRIPTOR.services_by_name['MyService'] = _MYSERVICE

# @@protoc_insertion_point(module_scope)
