# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Hello_pb2 as Hello__pb2


class TestStub(object):
    """定義 service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello0 = channel.unary_unary(
                '/Test/SayHello0',
                request_serializer=Hello__pb2.RequestType.SerializeToString,
                response_deserializer=Hello__pb2.ResponseType.FromString,
                )
        self.SayHello1 = channel.stream_unary(
                '/Test/SayHello1',
                request_serializer=Hello__pb2.RequestType.SerializeToString,
                response_deserializer=Hello__pb2.ResponseType.FromString,
                )
        self.SayHello2 = channel.unary_stream(
                '/Test/SayHello2',
                request_serializer=Hello__pb2.RequestType.SerializeToString,
                response_deserializer=Hello__pb2.ResponseType.FromString,
                )
        self.SayHello3 = channel.stream_stream(
                '/Test/SayHello3',
                request_serializer=Hello__pb2.RequestType.SerializeToString,
                response_deserializer=Hello__pb2.ResponseType.FromString,
                )


class TestServicer(object):
    """定義 service
    """

    def SayHello0(self, request, context):
        """可多組
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello1(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SayHello3(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello0': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello0,
                    request_deserializer=Hello__pb2.RequestType.FromString,
                    response_serializer=Hello__pb2.ResponseType.SerializeToString,
            ),
            'SayHello1': grpc.stream_unary_rpc_method_handler(
                    servicer.SayHello1,
                    request_deserializer=Hello__pb2.RequestType.FromString,
                    response_serializer=Hello__pb2.ResponseType.SerializeToString,
            ),
            'SayHello2': grpc.unary_stream_rpc_method_handler(
                    servicer.SayHello2,
                    request_deserializer=Hello__pb2.RequestType.FromString,
                    response_serializer=Hello__pb2.ResponseType.SerializeToString,
            ),
            'SayHello3': grpc.stream_stream_rpc_method_handler(
                    servicer.SayHello3,
                    request_deserializer=Hello__pb2.RequestType.FromString,
                    response_serializer=Hello__pb2.ResponseType.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Test', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Test(object):
    """定義 service
    """

    @staticmethod
    def SayHello0(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Test/SayHello0',
            Hello__pb2.RequestType.SerializeToString,
            Hello__pb2.ResponseType.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello1(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Test/SayHello1',
            Hello__pb2.RequestType.SerializeToString,
            Hello__pb2.ResponseType.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Test/SayHello2',
            Hello__pb2.RequestType.SerializeToString,
            Hello__pb2.ResponseType.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SayHello3(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Test/SayHello3',
            Hello__pb2.RequestType.SerializeToString,
            Hello__pb2.ResponseType.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
