# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Hello.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bHello.proto\",\n\x0bRequestType\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\" \n\x0cResponseType\x12\x10\n\x08sentence\x18\x01 \x01(\t2\xbe\x01\n\x04Test\x12*\n\tSayHello0\x12\x0c.RequestType\x1a\r.ResponseType\"\x00\x12,\n\tSayHello1\x12\x0c.RequestType\x1a\r.ResponseType\"\x00(\x01\x12,\n\tSayHello2\x12\x0c.RequestType\x1a\r.ResponseType\"\x00\x30\x01\x12.\n\tSayHello3\x12\x0c.RequestType\x1a\r.ResponseType\"\x00(\x01\x30\x01\x62\x06proto3'
)




_REQUESTTYPE = _descriptor.Descriptor(
  name='RequestType',
  full_name='RequestType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RequestType.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='RequestType.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=59,
)


_RESPONSETYPE = _descriptor.Descriptor(
  name='ResponseType',
  full_name='ResponseType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='ResponseType.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['RequestType'] = _REQUESTTYPE
DESCRIPTOR.message_types_by_name['ResponseType'] = _RESPONSETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestType = _reflection.GeneratedProtocolMessageType('RequestType', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTTYPE,
  '__module__' : 'Hello_pb2'
  # @@protoc_insertion_point(class_scope:RequestType)
  })
_sym_db.RegisterMessage(RequestType)

ResponseType = _reflection.GeneratedProtocolMessageType('ResponseType', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSETYPE,
  '__module__' : 'Hello_pb2'
  # @@protoc_insertion_point(class_scope:ResponseType)
  })
_sym_db.RegisterMessage(ResponseType)



_TEST = _descriptor.ServiceDescriptor(
  name='Test',
  full_name='Test',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=96,
  serialized_end=286,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello0',
    full_name='Test.SayHello0',
    index=0,
    containing_service=None,
    input_type=_REQUESTTYPE,
    output_type=_RESPONSETYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SayHello1',
    full_name='Test.SayHello1',
    index=1,
    containing_service=None,
    input_type=_REQUESTTYPE,
    output_type=_RESPONSETYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SayHello2',
    full_name='Test.SayHello2',
    index=2,
    containing_service=None,
    input_type=_REQUESTTYPE,
    output_type=_RESPONSETYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SayHello3',
    full_name='Test.SayHello3',
    index=3,
    containing_service=None,
    input_type=_REQUESTTYPE,
    output_type=_RESPONSETYPE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEST)

DESCRIPTOR.services_by_name['Test'] = _TEST

# @@protoc_insertion_point(module_scope)
